//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jolia.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RIO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RIO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jolia.Core.Resources.RIO", typeof(RIO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم قراءة الملف بنجاح.
        /// </summary>
        public static string FileReadSuccessfully {
            get {
                return ResourceManager.GetString("FileReadSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار ملف.
        /// </summary>
        public static string MustSelectFile {
            get {
                return ResourceManager.GetString("MustSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستند.
        /// </summary>
        public static string Type_DOC {
            get {
                return ResourceManager.GetString("Type_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفات أخرى.
        /// </summary>
        public static string Type_File {
            get {
                return ResourceManager.GetString("Type_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور.
        /// </summary>
        public static string Type_IMG {
            get {
                return ResourceManager.GetString("Type_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف الكتروني.
        /// </summary>
        public static string Type_PDF {
            get {
                return ResourceManager.GetString("Type_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض تقديمي.
        /// </summary>
        public static string Type_PPT {
            get {
                return ResourceManager.GetString("Type_PPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستند نصي.
        /// </summary>
        public static string Type_TXT {
            get {
                return ResourceManager.GetString("Type_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول الكتروني.
        /// </summary>
        public static string Type_XLS {
            get {
                return ResourceManager.GetString("Type_XLS", resourceCulture);
            }
        }
    }
}
